language: objective-c
osx_image: xcode10.2
xcode_project: Cuckoo.xcodeproj
xcode_scheme: Cuckoo
xcode_sdk: macosx

before_script:
    - pod install --repo-update

script:
    - xcodebuild -workspace 'Cuckoo.xcworkspace' -scheme 'Cuckoo+OCMock-macOS' clean test | xcpretty
    - pod lib lint

after_script:
    - sleep 5
